# Generated by Django 4.2.14 on 2024-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='untitled', max_length=200),
            preserve_default=False,
        ),
    ]
